'use strict';
const D=JSON.parse(document.getElementById('orb-data').textContent), $=s=>document.querySelector(s), P=D.points, ids=new Map(P.map((p,i)=>[p.id,i]));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='orb-olympic-progress-v1', reduced=matchMedia('(prefers-reduced-motion: reduce)');
let current=0, journey=0, mode='journey', visited=new Set([P[0].id]), trail=[P[0].id], history=[], mediaIndex=0, motion=!reduced.matches;
let yaw=0,targetYaw=0,lastInteraction=performance.now(),hover=-1,projected=[],drag=null,statusTimer;
const directions={up:'↑ Up · Broader',down:'↓ Down · Deeper',left:'← Left · Adjacent facet',right:'Right · Adjacent facet →',backward:'↶ Backward · Thread',forward:'Forward · Thread ↷'};
function message(t){$('#status').textContent=t;clearTimeout(statusTimer);statusTimer=setTimeout(()=>{$('#status').textContent=''},5000)}
function validState(s){return s&&s.orbId===D.id&&s.schemaVersion===1&&ids.has(s.current)&&ids.has(s.journeyPoint)&&['journey','browse'].includes(s.mode)&&Array.isArray(s.visited)&&s.visited.length<=P.length&&s.visited.every(x=>ids.has(x))&&Array.isArray(s.trail)&&s.trail.length<=100&&s.trail.every(x=>ids.has(x))&&Array.isArray(s.history)&&s.history.length<=100&&s.history.every(x=>ids.has(x))}
function applyState(s){current=ids.get(s.current);journey=ids.get(s.journeyPoint);mode=s.mode;visited=new Set(s.visited);visited.add(P[current].id);trail=s.trail;history=s.history}
function snapshot(){const p=P[current];return {schemaVersion:1,orbId:D.id,root:D.root,edition:D.authored,current:p.id,journeyPoint:P[journey].id,mode,style:'active',visited:[...visited],trail:trail.slice(-100),history:history.slice(-100),savedAt:new Date().toISOString(),currentContext:{reading:p.paragraphs,kind:p.kind,boundaryType:p.boundaryType||null,knownBasis:p.knownBasis||null,openQuestion:p.openQuestion||null,uncertainty:p.uncertainty||null,researchApproach:p.researchApproach||null,sources:p.sources.map(k=>D.sources[k]),links:p.links},registry:[{id:D.id,parent:null,anchor:D.title,lastVisited:p.id}],visitedFloorPoints:[...visited].map(id=>P[ids.get(id)]).filter(x=>x.kind==='floor').map(x=>({id:x.id,knownBasis:x.knownBasis,openQuestion:x.openQuestion,uncertainty:x.uncertainty,sources:x.sources.map(k=>D.sources[k])}))}}
function persist(){try{localStorage.setItem(key,JSON.stringify(snapshot()))}catch{}}
let restoredCurrent=null;
try{const s=JSON.parse(localStorage.getItem(key));if(validState(s)){applyState(s);restoredCurrent=s.current}}catch{}
try{const id=decodeURIComponent(location.hash.slice(1));if(ids.has(id)){current=ids.get(id);if(id!==restoredCurrent){journey=current;mode='journey'}visited.add(id);if(trail.at(-1)!==id)trail.push(id)}}catch{}
function target(){const a=current/(P.length-1)*Math.PI*8.3;targetYaw=-a;targetYaw+=Math.round((yaw-targetYaw)/(Math.PI*2))*Math.PI*2;lastInteraction=performance.now();if(reduced.matches)yaw=targetYaw}
function imageForPoint(){const p=P[current],m=D.media[p.mediaPack[mediaIndex]];$('#point-image').src=m.data||m.file;$('#point-image').alt=m.alt;$('#photo-frame').classList.toggle('contain',m.fit==='contain'||p.mediaPack[mediaIndex]==='ice');$('#caption').innerHTML=esc(m.caption)+' '+(m.kind==='illustration'?esc(m.credit)+' · ':'')+'<a target="_blank" rel="noopener" href="'+esc(m.source)+'">'+esc(m.kind==='illustration'?'Conceptual source':m.credit)+' ↗</a>';$('#media-picker').innerHTML=p.mediaPack.length>1?p.mediaPack.map((k,i)=>`<button data-media="${i}" aria-label="Show image ${i+1}: ${esc(D.media[k].caption)}" aria-pressed="${i===mediaIndex}">${i+1}</button>`).join(''):''}
function render(){const p=P[current],floor=p.kind==='floor';const restUrl=location.protocol==='file:'?'https://visualizationcreation.github.io/olympic-national-park/rest.html':'rest.html';$('#rest-link').href=restUrl+'?start=beginning';$('#rest-point-link').href=restUrl+'#'+p.id;document.title=p.title+' · Olympic ORB';$('#point-meta').textContent=`${String(current+1).padStart(2,'0')} / 30 · ${p.chapter}`;const words=(p.paragraphs.join(' ')+' '+(p.researchApproach||'')+' '+(p.openQuestion||'')).split(/\s+/).length;$('#reading-time').textContent=`${Math.max(1,Math.ceil(words/180))} min read`;$('#point-title').textContent=p.title;$('#deck').textContent=p.deck;$('#reading').innerHTML=p.paragraphs.map(t=>'<p>'+esc(t)+'</p>').join('');$('#floor-question').hidden=!floor;$('#research-method').hidden=!floor;$('#question').textContent=p.openQuestion||'';$('#method').textContent=p.researchApproach||'';$('#notice').innerHTML='<strong>'+(floor?'Question status':'A closer look')+'</strong> · '+esc(p.notice);$('#source-list').innerHTML=p.sources.map(k=>`<li><a href="${esc(D.sources[k].url)}" target="_blank" rel="noopener">${esc(D.sources[k].title)} ↗</a></li>`).join('');$('#sources-title').textContent=`Evidence & further reading · ${p.sources.length} source${p.sources.length===1?'':'s'}`;$('#directions').innerHTML=Object.entries(directions).map(([d,label])=>{const e=p.links[d];return `<button data-direction="${d}" ${e.to===null?'disabled':''}><strong>${label}</strong><span>${e.to===null?'Edge of this edition':esc(P[ids.get(e.to)].title)}</span><small>${esc(e.label)}</small></button>`}).join('');$('#map-current').innerHTML=`<small>${floor?'KNOWLEDGE FLOOR':'POINT '+String(current+1).padStart(2,'0')+' / 30'}</small>${esc(p.title)}`;$('#visited-count').textContent=visited.size+' of 30 visited';$('#history-back').disabled=!history.length;$('#trail-list').innerHTML=trail.slice(-4).map(id=>`<button data-point="${ids.get(id)}">${esc(P[ids.get(id)].title)}</button>`).join(' <span aria-hidden="true">→</span> ');$('#journey-status').textContent=mode==='journey'?`Full spiral · ${journey+1} of 30 · Self-paced`:`Free exploration · Spiral parked at ${journey+1} of 30`;$('#bridge').textContent=mode==='journey'?p.bridge:'Follow the compass to explore connections, or return to your place in the reading journey.';$('#resume').hidden=mode==='journey';$('#previous').hidden=mode!=='journey';$('#next').hidden=mode!=='journey';$('#previous').disabled=journey===0;$('#next').textContent=journey===P.length-1?'Return to the beginning ↗':'Next in spiral →';$('#motion').textContent=motion?'Pause rotation':'Enable rotation';$('#motion').setAttribute('aria-pressed',String(motion));$('#print-address').textContent='Point: '+D.id+'/'+p.id+' · '+location.href;imageForPoint();renderContents();persist()}
function select(i,{guided=false,addHistory=true,focus=true}={}){if(!Number.isInteger(i)||i<0||i>=P.length)return;if(addHistory&&current!==i)history.push(P[current].id);history=history.slice(-100);current=i;if(guided){journey=i;mode='journey'}else mode='browse';mediaIndex=0;visited.add(P[i].id);if(trail.at(-1)!==P[i].id)trail.push(P[i].id);trail=trail.slice(-100);try{window.history.replaceState(null,'','#'+P[i].id)}catch{}target();render();if(focus){$('#point-title').focus({preventScroll:true});$('#reader').scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'})}}
function renderContents(){const q=$('#search').value.toLocaleLowerCase().trim(),floorOnly=$('#filter').value==='floor';let count=0;$('#contents-list').innerHTML=P.map((p,i)=>{if(floorOnly&&p.kind!=='floor')return '';if(q&&!(p.title+' '+p.deck+' '+p.paragraphs.join(' ')+' '+(p.openQuestion||'')).toLocaleLowerCase().includes(q))return '';count++;return `<li><button data-point="${i}" aria-current="${i===current}"><b>${String(i+1).padStart(2,'0')}</b><span><small>${esc(p.chapter)}${visited.has(p.id)?' · Visited':''}</small>${esc(p.title)}</span></button></li>`}).join('');if(!count)$('#contents-list').innerHTML='<li class="no-results">No matching readings. Try another word.</li>'}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000)}
async function copy(text,success){try{await navigator.clipboard.writeText(text);message(success)}catch{$('#prompt').value=text;if(!$('#continuation').open)$('#continuation').showModal();$('#prompt').focus();$('#prompt').select();message('Select and copy the text shown here.')}}
function handoff(){const p=P[current];return `/orbiverse\nContinue from Olympic National Park, point "${p.title}" (${D.id}/${p.id}).\nRoot anchor: Olympic National Park. Current relevance: in view.\nMode: ${mode}; Active Journey reading edition; spiral parked at ${P[journey].id}.\n\nReading:\n${p.paragraphs.join('\n\n')}\n\n${p.kind==='floor'?`Knowledge floor — ${p.boundaryType}\nKnown basis: ${p.knownBasis}\nOpen question: ${p.openQuestion}\nUncertainty: ${p.uncertainty}\nProposed investigation: ${p.researchApproach}\nKeep this question unresolved unless new evidence supports an answer.\n\n`:''}Sources:\n${p.sources.map(k=>D.sources[k].title+' — '+D.sources[k].url).join('\n')}\n\nCompass:\n${Object.entries(p.links).map(([d,e])=>d.toUpperCase()+': '+(e.to||'authored edge')+' — '+e.label).join('\n')}\n\nVisited trail: ${trail.join(' → ')}\nContinue with a related ORB grounded in these sources. Distinguish supported findings, hypotheses and unresearched terrain. DOWN may explore finer scale or deeper explanation. Preserve the root connection and offer a route back.`}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.point!==undefined){select(Number(b.dataset.point));if($('#contents').open)$('#contents').close()}if(b.dataset.direction){const to=P[current].links[b.dataset.direction].to;if(to)select(ids.get(to))}if(b.dataset.media!==undefined){mediaIndex=Number(b.dataset.media);imageForPoint()}if(b.dataset.close)document.getElementById(b.dataset.close).close()});
$('#contents-open').onclick=()=>{$('#contents').showModal();$('#search').focus()};$('#search').oninput=renderContents;$('#filter').onchange=renderContents;
$('#previous').onclick=()=>select(journey-1,{guided:true});$('#next').onclick=()=>select(journey===P.length-1?0:journey+1,{guided:true});$('#resume').onclick=()=>select(journey,{guided:true});
$('#history-back').onclick=()=>{const id=history.pop();if(id)select(ids.get(id),{addHistory:false})};
$('#motion').onclick=()=>{motion=!motion;lastInteraction=performance.now();targetYaw=yaw;render()};
reduced.addEventListener('change',()=>{if(reduced.matches){motion=false;yaw=targetYaw;render()}});
$('#save').onclick=()=>{download('olympic-orb-checkpoint.json',JSON.stringify(snapshot(),null,2),'application/json');message('Checkpoint saved with your route, sources and open questions.')};
$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('size');const s=JSON.parse(await f.text());if(!validState(s))throw Error('shape');applyState(s);mediaIndex=0;window.history.replaceState(null,'','#'+P[current].id);target();render();message('Your Olympic ORB checkpoint is restored.')}catch{message('This file is not a valid Olympic ORB checkpoint. Your current route is unchanged.')}e.target.value=''};
$('#offline').onclick=()=>{download('olympic-national-park.html','<!doctype html>\n'+document.documentElement.outerHTML,'text/html');message('Self-contained HTML saved. Source links still need an internet connection.')};
$('#print').onclick=()=>{$('#sources').open=true;window.print()};$('#handoff').onclick=()=>{$('#prompt').value=handoff();$('#continuation').showModal()};$('#copy-prompt').onclick=()=>copy($('#prompt').value,'Continuation copied. Paste it into your ORB conversation.');$('#point-link').onclick=()=>copy('https://visualizationcreation.github.io/olympic-national-park/#'+P[current].id,'Direct link to this point copied.');
window.addEventListener('hashchange',()=>{try{const id=decodeURIComponent(location.hash.slice(1));if(ids.has(id))select(ids.get(id),{focus:false})}catch{}});
// The display spiral records lesson order, independently of all conceptual edges.
const canvas=$('#orb'),ctx=canvas.getContext('2d');let W=400,H=400,ratio=1;
function resize(){const r=canvas.getBoundingClientRect();W=r.width;H=r.height;ratio=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*ratio);canvas.height=Math.round(H*ratio);ctx.setTransform(ratio,0,0,ratio,0,0)}
new ResizeObserver(resize).observe(canvas);resize();
function position(t,rotation=yaw){const y=.93-1.86*t,a=t*Math.PI*8.3+rotation,r=Math.sqrt(1-y*y),x=r*Math.sin(a),z=r*Math.cos(a),scale=Math.min(W,H)*.37;return {x:W/2+x*scale,y:H/2-y*scale,z,scale}}
function draw(now){const r=Math.min(W,H)*.37,cx=W/2,cy=H/2;ctx.clearRect(0,0,W,H);const glow=ctx.createRadialGradient(cx-r*.22,cy-r*.28,r*.1,cx,cy,r*1.24);glow.addColorStop(0,'#305248');glow.addColorStop(.72,'#173c33');glow.addColorStop(1,'rgba(16,46,41,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,r*1.24,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#406052';ctx.lineWidth=.7;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.stroke();
 for(const y of [-.65,-.3,.3,.65]){const rx=Math.sqrt(1-y*y)*r;ctx.strokeStyle='#53716335';ctx.beginPath();ctx.ellipse(cx,cy-y*r,rx,rx*.11,0,0,Math.PI*2);ctx.stroke()}
 for(let k=0;k<260;k++){const a=position(k/260),b=position((k+1)/260);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineWidth=a.z>0?1.2:.7;ctx.strokeStyle=a.z>0?'rgba(204,225,167,.65)':'rgba(164,193,150,.17)';ctx.stroke()}
 projected=P.map((p,i)=>({...position(i/(P.length-1)),i}));const sorted=[...projected].sort((a,b)=>a.z-b.z);for(const p of sorted){const active=p.i===current,isFloor=P[p.i].kind==='floor',v=visited.has(P[p.i].id),size=active?6.5:(p.z>0?3.8:2.5);ctx.beginPath();ctx.arc(p.x,p.y,size,0,Math.PI*2);ctx.fillStyle=active?'#f4f2d8':(isFloor?(p.z>0?'#c9d6ae':'#65806a'):(v?'#b9d494':(p.z>0?'#97b3a4':'#47685b')));ctx.fill();if(active){ctx.beginPath();ctx.arc(p.x,p.y,12,0,Math.PI*2);ctx.strokeStyle='#d8e8b7';ctx.lineWidth=1;ctx.stroke();ctx.fillStyle='#eef2db';ctx.font='11px Segoe UI';ctx.textAlign=p.x>cx?'right':'left';ctx.fillText(String(p.i+1).padStart(2,'0'),p.x+(p.x>cx?-19:19),p.y+4)}}
 if(hover>=0&&hover!==current){const p=projected[hover],label=P[hover].title;ctx.font='11px Segoe UI';const tw=ctx.measureText(label).width,x=Math.max(10,Math.min(W-tw-18,p.x-tw/2));ctx.fillStyle='#f0f2e6';ctx.fillRect(x-6,p.y-31,tw+12,23);ctx.fillStyle='#14392e';ctx.textAlign='left';ctx.fillText(label,x,p.y-15)}
}
let last=performance.now();function frame(now){const dt=Math.min(now-last,60)/1000;last=now;if(!reduced.matches&&Math.abs(targetYaw-yaw)>.0008)yaw+=(targetYaw-yaw)*(1-Math.exp(-dt*4));else if(motion&&!reduced.matches&&!drag&&now-lastInteraction>7000){yaw+=dt*.055;targetYaw=yaw}draw(now);requestAnimationFrame(frame)}
function hit(x,y){return projected.filter(p=>Math.hypot(p.x-x,p.y-y)<14).sort((a,b)=>b.z-a.z)[0]?.i??-1}
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();drag={x:e.clientX,y:e.clientY,yaw,moved:false};lastInteraction=performance.now();canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();if(drag&&Math.abs(e.clientX-drag.x)>7){drag.moved=true;yaw=drag.yaw+(e.clientX-drag.x)*.012;targetYaw=yaw;lastInteraction=performance.now()}else{hover=hit(e.clientX-r.left,e.clientY-r.top);canvas.style.cursor=hover>=0?'pointer':'grab'}});
canvas.addEventListener('pointerup',e=>{if(drag&&!drag.moved){const r=canvas.getBoundingClientRect(),i=hit(e.clientX-r.left,e.clientY-r.top);if(i>=0)select(i)}drag=null});canvas.addEventListener('pointercancel',()=>{drag=null});canvas.addEventListener('pointerleave',()=>{hover=-1});
target();yaw=targetYaw;render();requestAnimationFrame(frame);
