'use strict';
const DATA=window.OLYMPIC_COURSES,$=s=>document.querySelector(s),audio=$('#course-audio'),preload=$('#next-audio'),canvas=$('#course-orb'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=t=>{t=Math.max(0,Math.floor(t||0));return Math.floor(t/60)+':'+String(t%60).padStart(2,'0')};
const names={learn:'ORB Learn',feel:'ORB Feel & Experience'},aliases={active:'learn',rest:'feel',learn:'learn',feel:'feel'};
let mode=aliases[new URLSearchParams(location.search).get('mode')]||'learn',course=DATA.courses[mode],pointIndex=0,chapterIndex=-1,globalTime=0,lastPoint=-1,lastPara=-1,busy=false,token=0,motion=!reduced.matches,yaw=0,targetYaw=0,boxes=[],w=400,h=448,saveAt=0,complete=false,tracking=false;
const chapterCache=new Map();
async function chapterSource(file){if(location.protocol==='file:')return file;if(!chapterCache.has(file)){chapterCache.set(file,fetch(file).then(r=>{if(!r.ok)throw Error('Narration could not load.');return r.blob()}).then(b=>URL.createObjectURL(b)).catch(e=>{chapterCache.delete(file);throw e}));}return chapterCache.get(file)}
const stored={};for(const key of ['learn','feel']){try{stored[key]=JSON.parse(localStorage.getItem('olympic-course-'+key))}catch{}}
function say(s){$('#course-status').textContent=s}
function savedPlace(){const v=stored[mode];if(!v||v.orbId!==DATA.orbId||!course.points.some(p=>p.id===v.pointId))return null;const time=v.revision===course.scriptRevision&&Number.isFinite(v.time)?v.time:course.points.find(p=>p.id===v.pointId).start;return time>0.5&&time<course.duration-1?{...v,time}:null}
function updateResume(){const s=savedPlace();$('#resume-saved').hidden=!s;$('#resume-saved').textContent=s?'Resume your spiral · '+fmt(s.time)+' · '+course.points.find(p=>p.id===s.pointId).label:'Resume your spiral'}
function save(){if(busy||!tracking||!Number.isFinite(globalTime))return;stored[mode]={orbId:DATA.orbId,mode,revision:course.scriptRevision,pointId:course.points[pointIndex].id,time:globalTime};try{localStorage.setItem('olympic-course-'+mode,JSON.stringify(stored[mode]))}catch{}updateResume()}
function pointAt(t){return Math.max(0,course.points.findLastIndex(p=>p.start<=t+.001))}
function controls(){const ready=!busy;for(const id of ['start','play','listen-point','back15','forward15','resume-saved'])$('#'+id).disabled=!ready;$('#play').textContent=audio.paused?(complete?'Replay':'Play / continue'):'Pause';$('#motion').textContent=motion?'Motion on':'Motion off';$('#motion').setAttribute('aria-pressed',String(motion));$('#course-orb').setAttribute('aria-label',`Course spiral: point ${pointIndex+1} of 72, ${course.points[pointIndex].title}. Use the point selector to navigate.`)}
function render(t){globalTime=Math.max(0,Math.min(course.duration,t));pointIndex=pointAt(globalTime);const p=course.points[pointIndex],ci=Math.max(0,p.cues.findLastIndex(c=>c.start<=globalTime+.001));if(lastPoint!==pointIndex){lastPoint=pointIndex;lastPara=-1;const im=DATA.media[p.media];$('#point-counter').textContent=`POINT ${String(pointIndex+1).padStart(2,'0')} / 72`;$('#sphere-title').textContent=p.label;$('#point-title').textContent=p.title;$('#chapter-name').textContent=p.chapter+(p.kind==='floor'?' · OPEN INVESTIGATION':'');$('#point-select').value=p.id;$('#course-reading').innerHTML=p.paragraphs.map(s=>'<p>'+esc(s)+'</p>').join('');$('#course-image').src=im.file;$('#course-image').alt=im.alt;$('#course-image').classList.toggle('contain',im.kind==='illustration'||im.fit==='contain'||im.height>im.width);$('#image-caption').innerHTML=esc(im.caption)+' <span>'+esc(im.credit)+'</span> '+(im.source?'<a href="'+esc(im.source)+'" target="_blank" rel="noopener">Source ↗</a>':'');$('#course-sources').innerHTML=p.sources.map(k=>'<li><a href="'+esc(DATA.sources[k].url)+'" target="_blank" rel="noopener">'+esc(DATA.sources[k].title)+' ↗</a></li>').join('');$('#explore-point').href='index.html#'+p.id;targetYaw=-pointIndex/71*Math.PI*8.3;targetYaw+=Math.round((yaw-targetYaw)/(Math.PI*2))*Math.PI*2;if(!motion)yaw=targetYaw;history.replaceState(null,'','?mode='+mode+'#'+p.id);controls()}
if(ci!==lastPara){lastPara=ci;$('#course-reading').querySelectorAll('p').forEach((e,i)=>e.classList.toggle('speaking',i===ci))}$('#elapsed').textContent=fmt(globalTime);$('#seek').value=globalTime;}
async function position(t,play=false,persist=true){
const mine=++token;busy=true;audio.pause();complete=false;controls();t=Math.max(0,Math.min(course.duration,t));
const k=Math.max(0,course.chapters.findLastIndex(c=>c.start<=t+.001)),chapter=course.chapters[k];
try{
 if(k!==chapterIndex){say('Loading narration…');const src=await chapterSource(chapter.file);if(mine!==token)return;audio.src=src;audio.load();
 await new Promise((resolve,reject)=>{if(audio.readyState>=1)return resolve();const clean=()=>{audio.removeEventListener('loadedmetadata',ok);audio.removeEventListener('error',bad);clearTimeout(timer)},ok=()=>{clean();resolve()},bad=()=>{clean();reject(Error('Narration could not load.'))},timer=setTimeout(()=>{clean();reject(Error('Narration loading timed out. Please select the point again.'))},25000);audio.addEventListener('loadedmetadata',ok,{once:true});audio.addEventListener('error',bad,{once:true})});
 if(mine!==token)return;if(Math.abs(audio.duration-chapter.duration)>.25)throw Error('Audio duration does not match this course.');chapterIndex=k;
 }
 if(mine!==token)return;
 const local=Math.min(audio.duration,Math.max(0,t-chapter.start));audio.currentTime=local;
 if(audio.seeking)await new Promise((resolve,reject)=>{const clean=()=>{audio.removeEventListener('seeked',ok);clearTimeout(timer)},ok=()=>{clean();resolve()},timer=setTimeout(()=>{clean();reject(Error('Audio seeking timed out. Please select the point again.'))},10000);audio.addEventListener('seeked',ok,{once:true})});
 if(mine!==token)return;if(Math.abs(audio.currentTime-local)>.15)throw Error('Audio could not reach this point. Please select it again.');
 render(t);tracking=persist;busy=false;controls();if(persist)save();
 const next=course.chapters[k+1];if(next)chapterSource(next.file).catch(()=>{});
 // Keep a small cache of the current and adjacent recordings.
 if(chapterCache.size>4)for(const [file,promise] of chapterCache){if(file!==chapter.file&&file!==next?.file){chapterCache.delete(file);promise.then(url=>{if(audio.src!==url)URL.revokeObjectURL(url)}).catch(()=>{});if(chapterCache.size<=4)break;}}
 if(play){await audio.play();say(names[mode]+' · Playing · Kokoro Bella')}else say('Ready at '+fmt(t)+'. Start from the top, or listen from this point.');
}catch(e){if(mine!==token)return;chapterIndex=-1;busy=false;controls();say(e.message)}
}
function setupMode(){course=DATA.courses[mode];$('#course-mode').value=mode;$('#course-label').textContent=names[mode];$('#mode-description').textContent=mode==='learn'?'Hear how the ideas connect, from mountain rock to coastal life.':'Settle into an imagined journey through the same living landscape.';$('#point-select').innerHTML=course.points.map((p,i)=>`<option value="${esc(p.id)}">${String(i+1).padStart(2,'0')} · ${esc(p.label)}</option>`).join('');$('#duration').textContent=fmt(course.duration);$('#seek').max=course.duration;$('#transcript-link').href=mode+'-course.md';$('#voice-label').textContent=course.voice+' · '+fmt(course.duration)+' · 72 points';$('#audio-downloads').innerHTML=course.chapters.map((c,i)=>'<a href="'+esc(c.file)+'" download>Audio '+(i+1)+' · '+esc(c.label)+'</a>').join('');$('#review-note').textContent='Source and script continuity reviewed; audio files and measured cues technically checked. A complete listening review of both recordings has not been performed.';document.title=names[mode]+' · Olympic Spiral Courses';lastPoint=-1;lastPara=-1;chapterIndex=-1;complete=false;tracking=false;updateResume()}
$('#course-mode').onchange=async e=>{save();audio.pause();const id=course.points[pointIndex].id;mode=e.target.value;setupMode();await position(course.points.find(p=>p.id===id)?.start||0,false,false);say('Mode changed at '+course.points[pointIndex].label+'. Press Play to listen.')};
$('#start').onclick=()=>position(0,true);$('#play').onclick=async()=>{if(complete)return position(0,true);if(!audio.paused){audio.pause();save();say('Paused at '+fmt(globalTime)+'.')}else try{await audio.play();say(names[mode]+' · Playing · Kokoro Bella')}catch(e){say('Playback could not start: '+e.message)}};
$('#resume-saved').onclick=()=>{const p=savedPlace();if(p)position(p.time,true)};$('#point-select').onchange=e=>position(course.points.find(p=>p.id===e.target.value).start,false);$('#listen-point').onclick=()=>position(course.points[pointIndex].start,true);$('#seek').onchange=e=>position(Number(e.target.value),!audio.paused);$('#back15').onclick=()=>position(globalTime-15,!audio.paused);$('#forward15').onclick=()=>position(globalTime+15,!audio.paused);$('#volume').oninput=e=>audio.volume=Number(e.target.value);$('#explore-point').onclick=()=>{audio.pause();save()};$('#motion').onclick=()=>{motion=!motion;if(!motion)yaw=targetYaw;controls()};reduced.addEventListener('change',e=>{if(e.matches){motion=false;yaw=targetYaw;controls()}});
audio.addEventListener('timeupdate',()=>{if(busy||chapterIndex<0)return;render(course.chapters[chapterIndex].start+audio.currentTime);if(Math.abs(globalTime-saveAt)>5){saveAt=globalTime;save()}});audio.addEventListener('play',()=>{tracking=true;controls()});audio.addEventListener('pause',()=>{controls();if(!busy)save()});audio.addEventListener('ended',()=>{if(busy)return;const next=course.chapters[chapterIndex+1];if(next)position(next.start,true);else{render(course.duration);complete=true;save();controls();say('Spiral complete. Explore any point, or start again from the top.')}});audio.addEventListener('error',()=>{if(!busy)say('Audio could not load. The transcript and sources remain available.')});window.addEventListener('pagehide',()=>{audio.pause();save()});
$('#print-course').onclick=()=>{audio.pause();$('#print-transcript').innerHTML='<h1>'+esc(course.title)+'</h1><p>Olympic National Park · '+fmt(course.duration)+' · Kokoro Bella</p>'+course.points.map((p,i)=>'<section><h2>'+(i+1)+'. '+esc(p.title)+'</h2>'+p.paragraphs.map(t=>'<p>'+esc(t)+'</p>').join('')+'<small>'+p.sources.map(k=>esc(DATA.sources[k].title)+' — '+esc(DATA.sources[k].url)).join('<br>')+'</small></section>').join('');window.print()};
new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const ratio=Math.min(devicePixelRatio||1,2);canvas.width=w*ratio;canvas.height=h*ratio;ctx.setTransform(ratio,0,0,ratio,0,0)}).observe(canvas);
function pos(t){const y=.92-1.84*t,r=Math.sqrt(1-y*y),a=t*Math.PI*8.3+yaw,R=Math.min(w,h)*.37;return{x:w/2+r*Math.sin(a)*R,y:h/2-y*R,z:r*Math.cos(a)}}
function draw(){if(motion)yaw+=(targetYaw-yaw)*(mode==='feel'?.025:.05);else yaw=targetYaw;ctx.clearRect(0,0,w,h);const R=Math.min(w,h)*.37,g=ctx.createRadialGradient(w*.42,h*.4,0,w/2,h/2,R*1.4);g.addColorStop(0,'#3f6650');g.addColorStop(1,'#133d33');ctx.fillStyle=g;ctx.beginPath();ctx.arc(w/2,h/2,R*1.25,0,Math.PI*2);ctx.fill();for(let j=0;j<350;j++){const a=pos(j/350),b=pos((j+1)/350);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=j/350<=pointIndex/71?(a.z>0?'#d4e5a5':'#8aa57560'):(a.z>0?'#77927670':'#52725a30');ctx.lineWidth=j/350<=pointIndex/71?1.5:.7;ctx.stroke()}const points=course.points.map((p,i)=>({...pos(i/71),i}));for(const p of [...points].sort((a,b)=>a.z-b.z)){ctx.beginPath();ctx.arc(p.x,p.y,p.i===pointIndex?6:2.5,0,Math.PI*2);ctx.fillStyle=p.i===pointIndex?'#eff4d4':p.z>0?'#bacd96':'#58745c';ctx.fill();if(p.i===pointIndex){ctx.beginPath();ctx.arc(p.x,p.y,12,0,Math.PI*2);ctx.strokeStyle='#c9e29a';ctx.stroke()}}boxes=[];for(const p of points.filter(p=>p.z>.15||p.i===pointIndex).sort((a,b)=>(b.i===pointIndex?10:0)+b.z-((a.i===pointIndex?10:0)+a.z))){const active=p.i===pointIndex;ctx.font=(active?'600 ':'400 ')+(active?13:11)+'px Segoe UI';const label=course.points[p.i].label,tw=ctx.measureText(label).width,x=Math.max(5,Math.min(w-tw-10,p.x+(p.x>w*.6?-tw-10:10))),y=p.y-8,box={x:x-3,y:y-9,w:tw+6,h:19,i:p.i};if(!active&&boxes.some(b=>box.x<b.x+b.w&&box.x+box.w>b.x&&box.y<b.y+b.h&&box.y+box.h>b.y))continue;boxes.push(box);ctx.fillStyle=active?'#d4e5a5':'#133d33d9';ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle=active?'#143b30':'#d6e3c6';ctx.textAlign='left';ctx.fillText(label,x,y+5)}requestAnimationFrame(draw)}
canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,b=boxes.find(b=>x>=b.x&&x<=b.x+b.w&&y>=b.y&&y<=b.y+b.h);if(b)position(course.points[b.i].start,false)};canvas.onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowRight'){e.preventDefault();position(course.points[Math.min(71,pointIndex+1)].start,false)}if(e.key==='ArrowUp'||e.key==='ArrowLeft'){e.preventDefault();position(course.points[Math.max(0,pointIndex-1)].start,false)}};
setupMode();let requested;try{requested=decodeURIComponent(location.hash.slice(1))}catch{}const first=course.points.find(p=>p.id===requested);render(first?.start||0);position(first?.start||0,false,false);requestAnimationFrame(draw);

