'use strict';
const S=window.OLYMPIC_REST,$=s=>document.querySelector(s),canvas=$('#film'),ctx=canvas.getContext('2d'),voice=$('#voice'),W=1920,H=1080,accent='#c7dca1';
const images=new Map(),placeKey='olympic-rest-place-v1',local=location.hostname==='127.0.0.1'&&location.port==='8774';
let ready=false,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches,busy=false,lastCue=-1,lastPoint=-1,lastSave=0;
let audioCtx=null,sourceNode=null,destination=null,recorder=null,testEnd=null,exportError=null;
const fmt=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`,status=t=>$('#status').textContent=t;
const cueAt=t=>Math.max(0,S.cues.findLastIndex(c=>c.start<=t+.001));
function text(t,x,y,size=24,color='#e7ecdf',font='Segoe UI',align='left'){ctx.font=`${size}px ${font}`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(t,x,y)}
function lines(t,width,size,font='Georgia'){ctx.font=`${size}px ${font}`;let out=[],row='';for(const w of t.split(/\s+/)){const n=row?row+' '+w:w;if(ctx.measureText(n).width>width&&row){out.push(row);row=w}else row=n}if(row)out.push(row);return out}
function wrapped(t,x,y,width,size=30,line=41,maxLines=6,color='#e7ecdf',font='Georgia'){let rows=lines(t,width,size,font);while(rows.length>maxLines&&size>19){size--;line=size*1.3;rows=lines(t,width,size,font)}rows.forEach((s,i)=>text(s,x,y+i*line,size,color,font));return rows.length}
function stroke(ps,color,width=1){ctx.beginPath();ctx.strokeStyle=color;ctx.lineWidth=width;ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}
function orb(t,k){const p=S.points[k],R=230,cx=300,cy=402,turns=Math.PI*8.3;const u=motion?Math.min(1,Math.max(0,(t-p.start)/2.5)):1,ease=u*u*(3-2*u);const lon=(Math.max(0,k-1)+(k?ease:0))/29*turns;const yaw=-lon+(motion?Math.sin(Math.max(0,t-p.start-2.5)/13)*.09:0);
const pos=q=>{const y=.93-1.86*q,r=Math.sqrt(1-y*y),a=q*turns+yaw;return{x:cx+r*Math.sin(a)*R,y:cy-y*R,z:r*Math.cos(a)}};
const glow=ctx.createRadialGradient(cx-45,cy-60,20,cx,cy,R);glow.addColorStop(0,'#365a50');glow.addColorStop(1,'#102e29');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(cx,cy,R,0,Math.PI*2);ctx.fill();
for(const y of [-.65,-.3,.3,.65]){ctx.beginPath();ctx.strokeStyle='#71958a30';ctx.ellipse(cx,cy-y*R,Math.sqrt(1-y*y)*R,Math.sqrt(1-y*y)*R*.12,0,0,Math.PI*2);ctx.stroke()}
let a=pos(0);for(let n=1;n<=260;n++){const b=pos(n/260);stroke([a,b],b.z>0?'#c7dca1a0':'#69885740',b.z>0?2:1);a=b}
S.points.map((_,i)=>({i,...pos(i/29)})).sort((a,b)=>a.z-b.z).forEach(p=>{const active=p.i===k;ctx.beginPath();ctx.arc(p.x,p.y,active?10:4.5,0,Math.PI*2);ctx.fillStyle=active?'#f4f2d8':p.z>0?'#adc793':'#56755e';ctx.fill();if(active){ctx.beginPath();ctx.arc(p.x,p.y,20,0,Math.PI*2);ctx.strokeStyle=accent;ctx.lineWidth=1.8;ctx.stroke()}});
text(`${String(k+1).padStart(2,'0')} / 30`,cx,685,26,accent,'Segoe UI','center');wrapped(p.kind==='floor'?'KNOWLEDGE FLOOR':p.chapter.toUpperCase(),80,728,440,20,27,2,'#aec5b6','Segoe UI');}
function photo(cue,t,alpha=1){const m=S.media[cue.asset],im=images.get(cue.asset),x=605,y=162,w=1251,h=485;ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle='#112d30';ctx.fillRect(x,y,w,h);if(im){const conceptual=m.kind==='illustration',portrait=im.height>im.width;const scale=(conceptual||portrait?Math.min(w/im.width,h/im.height):Math.max(w/im.width,h/im.height))*(motion&&!conceptual?1+.022*Math.max(0,Math.min(1,(t-cue.start)/(cue.end-cue.start))):1);ctx.beginPath();ctx.rect(x,y,w,h);ctx.clip();ctx.drawImage(im,x+(w-im.width*scale)/2,y+(h-im.height*scale)/2,im.width*scale,im.height*scale)}ctx.restore()}
function renderAt(t){const ci=cueAt(t),cue=S.cues[ci],k=cue.pointIndex,p=S.points[k],m=S.media[cue.asset];ctx.fillStyle='#091f24';ctx.fillRect(0,0,W,H);text('OLYMPIC NATIONAL PARK',64,77,43,'#f0eee1','Georgia');text('ORB JOURNEYS',1856,70,23,accent,'Segoe UI','right');stroke([{x:64,y:110},{x:1856,y:110}],'#38564a');wrapped(p.title,605,144,1251,30,38,1,'#e8eedf','Georgia');orb(t,k);photo(cue,t);if(motion&&k>0&&t-p.start<1){const previous=S.cues.findLast(c=>c.pointIndex===k-1);photo(previous,t,1-(t-p.start))}if(t>S.duration-13){ctx.fillStyle='#163a32';ctx.fillRect(605,162,1251,485);text('Your journey can continue.',670,330,54,'#f0eee1','Georgia');text('Explore the Olympic ORB at your own pace.',670,416,32,accent);text('visualizationcreation.github.io/olympic-national-park/',670,493,27,'#e7ecdf');text('LINK IN THE VIDEO DESCRIPTION',670,572,22,accent);text('Choose a point. Follow a question. Find another connection.',605,681,22,'#b9cbbf');text('ORB Journeys',605,739,20,'#a7beae')}else{wrapped(m.caption,605,681,1251,20,27,2,'#b9cbbf','Segoe UI');text((m.kind==='illustration'?'CONCEPTUAL ILLUSTRATION · ':'')+m.credit,605,739,20,'#a7beae')}stroke([{x:64,y:773},{x:1856,y:773}],'#38564a');wrapped(cue.text,64,820,1792,32,42,5);ctx.fillStyle='#38564a';ctx.fillRect(64,1042,1500,3);ctx.fillStyle=accent;ctx.fillRect(64,1042,1500*Math.min(1,t/S.duration),3);text('Rest Journey',1856,1050,27,accent,'Segoe UI','right');return ci}
function save(){if(!ready)return;const cue=S.cues[cueAt(voice.currentTime)];try{localStorage.setItem(placeKey,JSON.stringify({schemaVersion:1,orbId:S.orbId,style:'rest',scriptRevision:S.scriptRevision,pointId:cue.pointId,time:voice.currentTime}))}catch{}}
function jump(id,keepPlaying=false){const p=S.points.find(p=>p.id===id);if(!p)return;const was=!voice.paused;if(!keepPlaying)voice.pause();voice.currentTime=p.start;save();if(keepPlaying&&was)start()}
function update(t,ci){const cue=S.cues[ci],p=S.points[cue.pointIndex];$('#clock').textContent=fmt(t)+' / '+fmt(S.duration);$('#seek').value=t;$('#seek').max=S.duration;if(ci!==lastCue){lastCue=ci;canvas.setAttribute('aria-label',p.title+'. '+cue.text);if(cue.pointIndex!==lastPoint){lastPoint=cue.pointIndex;$('#reading-title').textContent=p.title;$('#reading').replaceChildren(...p.paragraphs.map(t=>{const el=document.createElement('p');el.textContent=t;return el}));$('#point-select').value=p.id;$('#point-status').textContent=`Point ${cue.pointIndex+1} of 30 · ${p.kind==='floor'?'Knowledge floor':p.chapter}`;$('#sources').replaceChildren(...p.sources.map(k=>{const li=document.createElement('li'),a=document.createElement('a');a.href=S.sources[k].url;a.textContent=S.sources[k].title+' ↗';a.target='_blank';a.rel='noopener';li.append(a);return li}));$('#credit').textContent=S.media[cue.asset].caption+' '+S.media[cue.asset].credit;$('#explore').href='index.html#'+p.id;history.replaceState(null,'','#'+p.id)}$('#reading').querySelectorAll('p').forEach((el,i)=>el.classList.toggle('speaking',i===cue.paragraphIndex))}if(t-lastSave>5){save();lastSave=t}}
function frame(){if(!busy||recorder?.state==='recording'){const t=voice.currentTime||0,ci=renderAt(t);update(t,ci);if(testEnd!==null&&t>=testEnd&&recorder?.state==='recording'){voice.pause();recorder.stop();testEnd=null}}requestAnimationFrame(frame)}
function transport(){$('#play').textContent=voice.paused?(voice.ended?'Replay journey':'Play journey'):'Pause';$('#motion').textContent=motion?'Motion on':'Motion off';$('#motion').setAttribute('aria-pressed',String(motion))}
async function start(){try{if(voice.ended)voice.currentTime=0;if(audioCtx)await audioCtx.resume();await voice.play();status('Playing Rest Journey · Microsoft Aria.')}catch(e){status('Playback could not start: '+e.message)}}
$('#play').onclick=()=>voice.paused?start():voice.pause();$('#seek').oninput=e=>{voice.currentTime=Number(e.target.value);save()};$('#point-select').onchange=e=>jump(e.target.value);$('#motion').onclick=()=>{motion=!motion;transport()};$('#explore').onclick=()=>{voice.pause();save()};$('#print').onclick=()=>{voice.pause();window.print()};voice.onplay=transport;voice.onpause=()=>{transport();save()};voice.onerror=()=>status('Narration could not load. The transcript remains available below.');voice.onended=()=>{transport();save();if(recorder?.state==='recording')recorder.stop();else status('Journey complete. Explore a point or listen again.')};
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
$('#save').onclick=()=>{save();download('olympic-rest-place.json',localStorage.getItem(placeKey),'application/json')};$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async e=>{try{const s=JSON.parse(await e.target.files[0].text());if(s.orbId!==S.orbId||s.style!=='rest'||!S.points.some(p=>p.id===s.pointId))throw Error('This is not an Olympic Rest Journey place.');voice.pause();voice.currentTime=s.scriptRevision===S.scriptRevision&&Number.isFinite(s.time)?Math.max(0,Math.min(S.duration,s.time)):S.points.find(p=>p.id===s.pointId).start;save();status('Rest Journey place restored.')}catch(e){status(e.message)}};
function lock(on){busy=on;document.querySelectorAll('button,input,select').forEach(el=>el.disabled=on);document.body.classList.toggle('exporting',on)}
async function record(test=false){if(!ready||busy)return;try{voice.pause();const requestedStart=test?Math.max(0,S.points[9].start-10):0;if(Math.abs(voice.currentTime-requestedStart)>.01)await new Promise(resolve=>{voice.addEventListener('seeked',resolve,{once:true});voice.currentTime=requestedStart});testEnd=test?requestedStart+25:null;if(!audioCtx){audioCtx=new AudioContext();sourceNode=audioCtx.createMediaElementSource(voice);destination=audioCtx.createMediaStreamDestination();sourceNode.connect(destination);sourceNode.connect(audioCtx.destination)}await audioCtx.resume();const visual=canvas.captureStream(30),stream=new MediaStream([...visual.getVideoTracks(),...destination.stream.getAudioTracks()]);const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)throw Error('WebM recording is unavailable in this browser.');let chunks=[];recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4500000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{voice.pause();visual.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:mime});lock(false);if(local&&test){const r=await fetch('/__recording-test',{method:'POST',body:blob});status(r.ok?'Transition test saved locally.':'Test save failed.')}else{const a=$('#record-download');a.href=URL.createObjectURL(blob);a.download='Olympic-Rest-Journey.webm';a.hidden=false;status('Recording complete. Download the WebM below.')}};lock(true);recorder.start(1000);await voice.play();status(test?'Recording a 25-second narrated transition test.':'Recording the full journey. Keep this page visible until it finishes.')}catch(e){lock(false);status('Recording failed: '+e.message)}}
$('#record').onclick=()=>record(false);$('#record-test').onclick=()=>record(true);
async function exportFrames(test){if(!local||!ready||busy)return;const fps=30,total=test?10:S.duration,count=Math.ceil(total*fps),start=test?Math.max(0,S.points[9].start-5):0;voice.pause();lock(true);exportError=null;let chunks=[],frameNo=0;try{const config={codec:'avc1.420028',width:W,height:H,bitrate:4500000,framerate:fps,avc:{format:'annexb'},hardwareAcceleration:'prefer-hardware',latencyMode:'quality'};const supported=await VideoEncoder.isConfigSupported(config);if(!supported.supported)throw Error('This browser cannot export H.264 frames at 1080p.');const init=await fetch('/__video-start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({test,fps,count,start,duration:total,scriptRevision:S.scriptRevision})});if(!init.ok)throw Error('Local export could not start.');const encoder=new VideoEncoder({output:c=>{const buf=new Uint8Array(c.byteLength);c.copyTo(buf);chunks.push(buf)},error:e=>{exportError=e}});encoder.configure(config);
const resumeFrames=(await init.json()).resumeFrames||0;for(frameNo=resumeFrames;frameNo<count;frameNo++){if(exportError)throw exportError;renderAt(Math.min(S.duration,start+frameNo/fps));const f=new VideoFrame(canvas,{timestamp:Math.round(frameNo*1e6/fps),duration:Math.round(1e6/fps)});encoder.encode(f,{keyFrame:frameNo%60===0});f.close();if(frameNo%120===119||frameNo===count-1){await encoder.flush();if(exportError)throw exportError;let response;const blob=new Blob(chunks);for(let attempt=0;attempt<4;attempt++){try{response=await fetch('/__video-chunk',{method:'POST',headers:{'X-Frames':String(frameNo+1)},body:blob});if(response.ok)break}catch(e){if(attempt===3)throw e}}chunks=[];if(!response?.ok)throw Error('Local frame save failed; saved progress can be resumed.');status(`Exporting ${test?'test':'full video'}: ${Math.round((frameNo+1)/count*100)}% · ${frameNo+1}/${count} frames`)}else if(encoder.encodeQueueSize>4)await new Promise(r=>encoder.addEventListener('dequeue',r,{once:true}))}
await encoder.flush();encoder.close();const done=await fetch('/__video-complete',{method:'POST'});if(!done.ok)throw Error('Could not finalize video frames.');status('Video frames saved. The local production helper can now combine them with the matching narration.')}catch(e){status('Video export stopped: '+e.message);await fetch('/__video-error',{method:'POST',body:String(e)}).catch(()=>{})}finally{lock(false);lastCue=-1}}
$('#export-test').onclick=()=>exportFrames(true);$('#export-full').onclick=()=>exportFrames(false);
S.points.forEach(p=>{const op=document.createElement('option');op.value=p.id;op.textContent=String(S.points.indexOf(p)+1).padStart(2,'0')+' · '+p.title;$('#point-select').append(op)});
async function init(){try{await Promise.all(Object.entries(S.media).map(([key,m])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images.set(key,im);resolve()};im.onerror=()=>reject(Error('Image could not load: '+m.file));im.src=m.file})));if(voice.readyState<1)await new Promise((resolve,reject)=>{voice.addEventListener('loadedmetadata',resolve,{once:true});voice.addEventListener('error',reject,{once:true})});if(Math.abs(voice.duration-S.duration)>.3)throw Error('Narration timing does not match this script.');let saved=null;try{saved=JSON.parse(localStorage.getItem(placeKey))}catch{}const hash=decodeURIComponent(location.hash.slice(1)),requested=S.points.find(p=>p.id===hash);if(saved?.scriptRevision===S.scriptRevision&&Number.isFinite(saved.time)&&(!requested||requested.id===saved.pointId))voice.currentTime=Math.max(0,Math.min(S.duration,saved.time));else if(requested)voice.currentTime=requested.start;ready=true;$('#play').disabled=false;for(const id of ['#record-test','#export-test','#export-full'])$(id).hidden=!local;status(`Ready · ${fmt(S.duration)} · Microsoft Aria · 30 points.`);transport()}catch(e){status('Could not prepare playback: '+e.message)}requestAnimationFrame(frame)}
window.addEventListener('pagehide',()=>{voice.pause();save()});matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(e.matches){motion=false;transport()}});init();
